apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
<<<<<<< HEAD
<<<<<<< HEAD
      securityContext:
        fsGroup: 65534
=======
>>>>>>> 5bca6c0... Initial setup of infrastructure as code setup prior to deployment automation
=======
      securityContext:
        fsGroup: 65534
>>>>>>> 339746b... worked on workflow and updated readme resolved all issues except efs mount
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: bitnami/external-dns:0.7.1
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=illumidesk.com # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
<<<<<<< HEAD
<<<<<<< HEAD
        - --registry=txt
        - --txt-owner-id=illumidesk
=======
>>>>>>> 5bca6c0... Initial setup of infrastructure as code setup prior to deployment automation
=======
        - --registry=txt
        - --txt-owner-id=illumidesk
>>>>>>> 339746b... worked on workflow and updated readme resolved all issues except efs mount

