kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-shared-volume
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi


      