imageCredentials:
  enabled: true
  registry: https://index.docker.io/v1/
  username: illumideskops
  password: vD9hD1qQ6fJ5lF8j
  email: hello@illumidesk.com
jupyterhub:
  debug:
    enabled: true
  proxy:
    secretToken: "asdfsdsf"
  singleuser:
    memory:
      limit: "1G"
      gurantee: "1G"
    storage:
      type: "static"
      static:
        pvcName: "shared-pvc-illumidesk"
        subPath: "illumidesk/home/{username}"
      extraVolumeMounts:
        - name: "home"
          mountPath: "/srv/nbgrader/exchange"
          subPath: "illumidesk/exchange/"
    defaultUrl: "/tree"
    image:
      name: "illumidesk/illumidesk-notebook"
      tag: "latest"
      pullPolicy: "Always"
  deploymentStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  hub:
    image:
      name: "illumidesk/jupyterhub"
      tag: "latest"
      pullPolicy: "Always"
    shutdownOnLogout: true
    extraEnv:
      CUSTOM_AUTH_TYPE: "LTI13"
      JUPYTERHUB_API_TOKEN: ""
      JUPYTERHUB_CRYPT_KEY: ""
      JUPYTERHUB_API_URL: "http://hub:8081/hub/api"
      LTI_CONSUMER_KEY: "lti_11_consumer_key"
      LTI_SHARED_SECRET: "lti_11_shared_secret"
      LTI13_CLIENT_ID: "125900000000000246"
      LTI13_ENDPOINT: "https://illumidesk.instructure.com/api/lti/security/jwks"
      LTI13_AUTHORIZE_URL: "https://illumidesk.instructure.com/api/lti/authorize_redirect"
      LTI13_TOKEN_URL: "https://illumidesk.instructure.com/login/oauth2/token"
      LTI13_PRIVATE_KEY: "/srv/jupyterhub/rsa_private.key" 
      OIDC_CLIENT_ID: ""
      OIDC_CLIENT_SECRET: ""
      OIDC_CALLBACK_URL: ""
      OIDC_AUTHORIZE_URL: ""
      OIDC_TOKEN_URL: ""
      OIDC_USERDATA_URL: ""
      ORGANIZATION_NAME: ""
      ILLUMIDESK_MNT_ROOT: "/illumidesk-courses"
      POSTGRES_NBGRADER_USER: "postgres"
      POSTGRES_NBGRADER_PASSWORD: ""
      POSTGRES_NBGRADER_HOST: "{{ namespace }}-postgresql.{{ namespace }}.svc.cluster.local"
      POSTGRES_JUPYTERHUB_HOST: "{{ namespace }}-postgresql.{{ namespace }}.svc.cluster.local"
      POSTGRES_JUPYTERHUB_DB: "illumidesk"
      POSTGRES_JUPYTERHUB_PORT: "5432"

albIngressController:
  enabled: false
  enableIRSA: false
  kube2iam: "arn:aws:iam::860100747351:instance-profile/k8s-alb-controller"
  clusterName: "illumidesk-staging"
  clusterVPC: ""
  awsRegion: "us-east-1"

albIngress:
  enabled: true
  host: "illumidesk-staging.illumidesk.com"
  ingress:
    annotations:
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/subnets: "subnet-0ab14d376ddf8f5c5,subnet-07495785b2373c393"
      alb.ingress.kubernetes.io/tags: "Environment=prod,Team=Prod"
      alb.ingress.kubernetes.io/group.name: "production"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:860100747351:certificate/fe1f513c-0784-4929-b6d2-c439f51ada0c"

allowNFS:
  enabled: false
  server: "fs-134885e6.efs.us-east-1.amazonaws.com"
  path: "/"

allowExternalDNS:
  enabled: false
  enableIRSA: false
  domainFilter: "illumidesk.com"
  txtOwnerID: "illumidesk"

datadog:
  enabled: false
  datadog:
    apiKey: ""
    site: "datadoghq.com"
    clusterName: ""
    clusterAgent:
      enabled: false
      token: ""
      metricsProvider:
        enabled: false

postgresql:
  enabled: false
  postgresqlUsername: "postgres"
  postgresqlPostgresPassword: ""
  postgresqlPassword: ""
  postgresqlDatabase: "illumidesk"

graderSetupService:
  enabled: true
  graderImage: "illumidesk/grader-notebook:latest"
  graderSetupImage: "illumidesk/grader-setup-app:latest"
  postgresNBGraderUser: "postgres"
  postgresNBGraderPassword: ""
  postgresNBGraderHost: "{{ namespace }}-postgresql.{{ namespace }}.svc.cluster.local"