apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyterhub 
  namespace: jupyterhub
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0f4f736964db5cb33,subnet-02d88c8f85aa8d545,subnet-09f376a470ceb9752
      #subnet-0eb7b025bedda5c83, subnet-01dd4852c83a7f091, subnet-0e4b38ea1e2a6f76d
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: jupyterhub.illumidesk.com

    http:
      paths:
      - path: /*
        backend:
          serviceName: proxy-public
          servicePort: 80