apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyterhub 
  namespace: jupyterhub
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0997ac5aad687fe5c,subnet-0f946b5f89d3358c8,subnet-04acf69878744f27d
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: jupyterhub.illumidesk.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: proxy-public
          servicePort: 80