hub:
  image:
    name: illumidesk/k8s-hub
    tag: latest
  shutdownOnLogout: true
proxy:
  https:
    enabled: false
  secretToken: ''
  service:
    ports:
      nodePort: 8080
    type: ClusterIP
singleuser:
  cmd: start-singleuser.sh
  extraEnv:
    CHOWN_HOME: 'yes'
    Editor: vim
  fsGid: 0
  image:
    name: illumidesk/base-notebook
    tag: latest
  storage:
    static:
      pvcName: jupyter-shared-volume
      subPath: home/{username}
    type: static
  uid: 0
